// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTAHFXjWUFziKbBAqZPa8tRhTTSjVpPOo',
    appId: '1:665472375451:web:20028d04138c55ebccc43e',
    messagingSenderId: '665472375451',
    projectId: 'shopping-app-c46d6',
    authDomain: 'shopping-app-c46d6.firebaseapp.com',
    storageBucket: 'shopping-app-c46d6.firebasestorage.app',
    measurementId: 'G-J5REW8YR6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPceGvgCJDqtJy3z1fhF9IKXMvN9tGSU0',
    appId: '1:665472375451:android:bcb0ffd77b5a679dccc43e',
    messagingSenderId: '665472375451',
    projectId: 'shopping-app-c46d6',
    storageBucket: 'shopping-app-c46d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlAvXbNFxGsvqF8eISDr6Fpv3YVooth6E',
    appId: '1:665472375451:ios:f23b7b8229f383a9ccc43e',
    messagingSenderId: '665472375451',
    projectId: 'shopping-app-c46d6',
    storageBucket: 'shopping-app-c46d6.firebasestorage.app',
    iosBundleId: 'com.example.newflutterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlAvXbNFxGsvqF8eISDr6Fpv3YVooth6E',
    appId: '1:665472375451:ios:f23b7b8229f383a9ccc43e',
    messagingSenderId: '665472375451',
    projectId: 'shopping-app-c46d6',
    storageBucket: 'shopping-app-c46d6.firebasestorage.app',
    iosBundleId: 'com.example.newflutterproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTAHFXjWUFziKbBAqZPa8tRhTTSjVpPOo',
    appId: '1:665472375451:web:69561d64cf5dd4ceccc43e',
    messagingSenderId: '665472375451',
    projectId: 'shopping-app-c46d6',
    authDomain: 'shopping-app-c46d6.firebaseapp.com',
    storageBucket: 'shopping-app-c46d6.firebasestorage.app',
    measurementId: 'G-1F4ELPCVB9',
  );
}
