// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANipyTnsoZedQKONBAjz1rrzwGmkie7_Q',
    appId: '1:722372607014:web:d8042e46aa9b0cf19f7ae7',
    messagingSenderId: '722372607014',
    projectId: 'authenticationtutorial-3fbe5',
    authDomain: 'authenticationtutorial-3fbe5.firebaseapp.com',
    storageBucket: 'authenticationtutorial-3fbe5.firebasestorage.app',
    measurementId: 'G-RT6FTL3862',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvtb8YgZuFicAbLMQHyG2tTvhjqwEhcr0',
    appId: '1:722372607014:android:d7f4866a727a99839f7ae7',
    messagingSenderId: '722372607014',
    projectId: 'authenticationtutorial-3fbe5',
    storageBucket: 'authenticationtutorial-3fbe5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuVIpgymlJqqmrdQ8x5gCmK7Hp4BG-5kc',
    appId: '1:722372607014:ios:d9017e63ead3c3119f7ae7',
    messagingSenderId: '722372607014',
    projectId: 'authenticationtutorial-3fbe5',
    storageBucket: 'authenticationtutorial-3fbe5.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuVIpgymlJqqmrdQ8x5gCmK7Hp4BG-5kc',
    appId: '1:722372607014:ios:d9017e63ead3c3119f7ae7',
    messagingSenderId: '722372607014',
    projectId: 'authenticationtutorial-3fbe5',
    storageBucket: 'authenticationtutorial-3fbe5.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANipyTnsoZedQKONBAjz1rrzwGmkie7_Q',
    appId: '1:722372607014:web:2d871798f2c969959f7ae7',
    messagingSenderId: '722372607014',
    projectId: 'authenticationtutorial-3fbe5',
    authDomain: 'authenticationtutorial-3fbe5.firebaseapp.com',
    storageBucket: 'authenticationtutorial-3fbe5.firebasestorage.app',
    measurementId: 'G-3EE88R1HJ8',
  );
}
